### ISSUE TITLE
external api help

### ISSUE THREAD

**Issue by johnlovespi** [johnlovespi/job_hunt2#3]
have couple questions on external api and rendering to page

@gittheking, @jasonseminara, @rapala61, @trevorpreston, @irwintsay

**Comment by gittheking** [comment]
@johnlovespi please be more specific with your issues - you could ask your questions here.

**Comment by rapala61** [comment]
@johnlovespi please follow the steps we have repeatedly asked you to follow. If you continue to create half baked issues, you will be skipped and wont be helped promptly.

Here are the steps:
https://git.generalassemb.ly/gist/bobbyking/3b7e8d65205a6a0580559cd304e1ce84

@gittheking

**Comment by johnlovespi** [comment]
Cant get external api to work 
i keep getting  "Super expression must either be null or a function, not undefined"
 its seems like i missing something in my constructor

i went to stack over flow and it said 
" ES6 keywords (extends) to subclass from a class which wasn't defined using ES6 class"
@mgershow

**Comment by trevorpreston** [comment]
JOHN.    I'll help you, but dude.

Your issues need to have:

1. Be able to accurately describe your issue
2. Identify the code snippet that is giving you an issue
3. Tell us 3 things that you tried in order to solve the issue
4. If there is an error message, tell us what that error message means
5. Assign all 5 instrctors on the issue

For example:
https://github.com/jaemin-han/Alarina_International/issues/7
